version: '3.9'

services:
  postgres:
    build: .
    container_name: postgres_vector
    environment:
      POSTGRES_USER: tibia_user
      POSTGRES_PASSWORD: tibia_pass
      POSTGRES_DB: tibia_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json

volumes:
  pgdata:
